# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_state', models.CharField(choices=[('acc', 'accepted'), ('decl', 'declined')], max_length=10)),
                ('receiver_state', models.CharField(choices=[('acc', 'accepted'), ('decl', 'declined')], max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
