# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='count_comments',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0435\u0432'),
        ),
        migrations.AddField(
            model_name='photo',
            name='count_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u043b\u0430\u0439\u043a\u043e\u0432'),
        ),
    ]
