# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useractivities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photocomment',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photocomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photolike',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photolike',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439', 'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': '\u041b\u0430\u0439\u043a', 'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438'},
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=None, max_length=255, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='PhotoComment',
        ),
        migrations.DeleteModel(
            name='PhotoLike',
        ),
    ]
