# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useractivities', '0002_auto_20160929_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_comments', models.PositiveIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0435\u0432')),
                ('count_likes', models.PositiveIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u043b\u0430\u0439\u043a\u043e\u0432')),
                ('when', models.DateTimeField(default=None, verbose_name='\u041a\u043e\u0433\u0434\u0430')),
            ],
            options={
                'abstract': False,
                'verbose_name': '\u0421\u043e\u0431\u044b\u0442\u0438\u0435',
                'verbose_name_plural': '\u0421\u043e\u0431\u044b\u0442\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043e\u0431\u044b\u0442\u0438\u044f')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u041b\u0430\u0439\u043a',
                'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_comments', models.PositiveIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0435\u0432')),
                ('count_likes', models.PositiveIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u043b\u0430\u0439\u043a\u043e\u0432')),
                ('description', models.TextField(default='\u0421\u043e\u0437\u0434\u0430\u0442\u0435\u043b\u044c \u0441\u043e\u0431\u044b\u0442\u0438\u044f, \u0443\u0432\u044b, \u0435\u0449\u0451 \u043d\u0435 \u043e\u0441\u0442\u0430\u0432\u0438\u043b \u0435\u0433\u043e \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('duration', models.TimeField(default=None, verbose_name='\u0414\u043b\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f')),
                ('when', models.DateTimeField(default=None, verbose_name='\u041a\u043e\u0433\u0434\u0430')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': '\u0421\u043e\u0431\u044b\u0442\u0438\u0435',
                'verbose_name_plural': '\u0421\u043e\u0431\u044b\u0442\u0438\u044f',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='count_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0427\u0438\u0441\u043b\u043e \u043b\u0430\u0439\u043a\u043e\u0432'),
        ),
    ]
